# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BgremoverCli < Formula
  desc ""
  homepage ""
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/root27/bgremover/releases/download/v1.0.1/bgremover_Darwin_x86_64.tar.gz"
      sha256 "1b41979ce887518dd885623cb5f77ef963df3bd7552dfe8f8288441e9cf4eabb"

      def install
        bin.install "bgremover-cli"
      end
    end
    on_arm do
      url "https://github.com/root27/bgremover/releases/download/v1.0.1/bgremover_Darwin_arm64.tar.gz"
      sha256 "bf0568ab3bf9c14c2954760f2af142f6676410e4a75d6c8587042c974ccdadd6"

      def install
        bin.install "bgremover-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.1/bgremover_Linux_x86_64.tar.gz"
        sha256 "6ce921762870af6c60a1aa7f21e557bb23b88eff394929f94d65072bbf72ef2f"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.1/bgremover_Linux_arm64.tar.gz"
        sha256 "264f222f2effbc03265057ba4591f7644272bdd1e97e929878bde0bcde0454ab"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
  end
end
