# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BgremoverCli < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/root27/bgremover/releases/download/v1.0.0/bgremover_Darwin_x86_64.tar.gz"
      sha256 "34b305d45d99580e6e457f20c496f60a5ffabda2a3ca5129741fa4d4d75182e7"

      def install
        bin.install "bgremover-cli"
      end
    end
    on_arm do
      url "https://github.com/root27/bgremover/releases/download/v1.0.0/bgremover_Darwin_arm64.tar.gz"
      sha256 "dad8ec48766386cc959b5d98b1441fd5f63dc2d5e2e2cb906ab3bb8f644fea37"

      def install
        bin.install "bgremover-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.0/bgremover_Linux_x86_64.tar.gz"
        sha256 "7184c0cc550a0e334bb0e5ae13e0821d4a89bec07ae7db728d25372c05bdd401"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.0/bgremover_Linux_arm64.tar.gz"
        sha256 "62973766186f30bd784438586823beec171550bb50fd72182e045a8e54ce3f8b"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
  end
end
