# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BgremoverCli < Formula
  desc ""
  homepage ""
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/root27/bgremover/releases/download/v1.0.3/bgremover_Darwin_x86_64.tar.gz"
      sha256 "50f37431d352fbcb63a2ed8821bf84844d98523b4a1631c7aa74f62e123769b9"

      def install
        bin.install "bgremover-cli"
      end
    end
    on_arm do
      url "https://github.com/root27/bgremover/releases/download/v1.0.3/bgremover_Darwin_arm64.tar.gz"
      sha256 "ce4df871d310e4ac35110c49a37276eda62e6bdb019694dd3f0c0ee656f249fb"

      def install
        bin.install "bgremover-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.3/bgremover_Linux_x86_64.tar.gz"
        sha256 "45c6f737201af9581b61cd5f373ef8eafe778cddda4bad48708c0d4f881f876e"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/bgremover/releases/download/v1.0.3/bgremover_Linux_arm64.tar.gz"
        sha256 "0641a98071715e268d901451834028bb54300aca51c980133220347bd34095d2"

        def install
          bin.install "bgremover-cli"
        end
      end
    end
  end
end
