# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCrypto < Formula
  desc ""
  homepage ""
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.7/go-crypto_1.0.7_darwin_arm64.tar.gz"
      sha256 "de0e9f2a25d2353baaa9929487a55af1cbe422a6b509a45e41b1a653e1d0449a"

      def install
        bin.install "go-crypto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.7/go-crypto_1.0.7_darwin_amd64.tar.gz"
      sha256 "e75d646d34f274245b38e926aaba778e82573897533572ef0fd5e4aad15fffc1"

      def install
        bin.install "go-crypto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.7/go-crypto_1.0.7_linux_arm64.tar.gz"
      sha256 "0a664e9a891a2aa86d12f99126311192f8fe018e579d230a6888fcdfb98021a2"

      def install
        bin.install "go-crypto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.7/go-crypto_1.0.7_linux_amd64.tar.gz"
      sha256 "e1adcf45d8755eca84c335efb11300474daf075c1ceae74dbfb93a978d3ab1be"

      def install
        bin.install "go-crypto"
      end
    end
  end
end
