# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCrypto < Formula
  desc ""
  homepage "https://github.com/root27/go-crypto"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.8/go-crypto_1.0.8_darwin_arm64.tar.gz"
      sha256 "b30bd456f0ca36494a34f5fd874eff7dc93ad3fb84c1b016e4e0209f750c0368"

      def install
        bin.install "go-crypto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.8/go-crypto_1.0.8_darwin_amd64.tar.gz"
      sha256 "b0ace68cd8015fcdd25d333e045395b14a60a307ddd7dab4fb6dd926d13e434a"

      def install
        bin.install "go-crypto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.8/go-crypto_1.0.8_linux_arm64.tar.gz"
      sha256 "d1ae9837460fc6447353a0a44b53110f70530f2bd35d74df720c062f2f321275"

      def install
        bin.install "go-crypto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-crypto/releases/download/v1.0.8/go-crypto_1.0.8_linux_amd64.tar.gz"
      sha256 "eea1a2629aefb90bc0419328311f2d581b4f031bed905f983fe880984a3ca157"

      def install
        bin.install "go-crypto"
      end
    end
  end
end
