# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPassword < Formula
  desc ""
  homepage ""
  version "1.1.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/root27/go-password/releases/download/v1.1.6/go-password_1.1.6_darwin_arm64.tar.gz"
      sha256 "e8707a2806b4e0e69ebe38b06a2666a0940815511aa18ffc984f39fbd08ea9cf"

      def install
        bin.install "go-password"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-password/releases/download/v1.1.6/go-password_1.1.6_darwin_amd64.tar.gz"
      sha256 "bdd9ba73467df319c29fd2d7821ce4949b0f2a37e1a56e75b2ea57c03295a9ec"

      def install
        bin.install "go-password"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/root27/go-password/releases/download/v1.1.6/go-password_1.1.6_linux_arm64.tar.gz"
      sha256 "317b8c2d75f3b91f33555887ae8de8f98aa21eedb51b2d6b673e81b6ce56c4f6"

      def install
        bin.install "go-password"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/root27/go-password/releases/download/v1.1.6/go-password_1.1.6_linux_amd64.tar.gz"
      sha256 "004d062023e68c13b7d991151ef7463df63b5150cbd81b52dfb8735492cc2197"

      def install
        bin.install "go-password"
      end
    end
  end
end
