# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hook < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/root27/hook/releases/download/v0.1.0/hook_Darwin_x86_64.tar.gz"
      sha256 "f8215174d52cc40e91cff338bb7a911ffa77f2077f1e01ae0a65e9753f4ee6d7"

      def install
        bin.install "hook"
      end
    end
    on_arm do
      url "https://github.com/root27/hook/releases/download/v0.1.0/hook_Darwin_arm64.tar.gz"
      sha256 "d4fbb4020662c0942e3458798de7463b591850e80a56c4cd2dd4e6e77f9e14df"

      def install
        bin.install "hook"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/hook/releases/download/v0.1.0/hook_Linux_x86_64.tar.gz"
        sha256 "b8d91502cc204b5df199bfbf915405adf8eaa79d2147849e89e7582f0285b707"

        def install
          bin.install "hook"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/hook/releases/download/v0.1.0/hook_Linux_arm64.tar.gz"
        sha256 "d54ef1856b4cabfd221e24b3e065f3aa3f728e11f8a60a5ffab65730217b3d19"

        def install
          bin.install "hook"
        end
      end
    end
  end
end
