# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slackmq < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/root27/slacknotifyMQ/releases/download/v0.0.1/slacknotifyMQ_Darwin_x86_64.tar.gz"
      sha256 "8e088979d14f06d968f38d8ad12877fbf47452be3c88ef7676ff77591a826804"

      def install
        bin.install "slackMQ"
      end
    end
    on_arm do
      url "https://github.com/root27/slacknotifyMQ/releases/download/v0.0.1/slacknotifyMQ_Darwin_arm64.tar.gz"
      sha256 "90fee4f785968659eba41e9df44d1d58e11b020ceeb24e6cf899c204dd879865"

      def install
        bin.install "slackMQ"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/slacknotifyMQ/releases/download/v0.0.1/slacknotifyMQ_Linux_x86_64.tar.gz"
        sha256 "07eac899ca6bc56fa4b4e551d438040064604f79fbfff07edc6b31630e12a4ea"

        def install
          bin.install "slackMQ"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/slacknotifyMQ/releases/download/v0.0.1/slacknotifyMQ_Linux_arm64.tar.gz"
        sha256 "147625324164e46e087878141e42fc7b92da358ebd00c74d7cf6f9166515ac8f"

        def install
          bin.install "slackMQ"
        end
      end
    end
  end
end
