# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termongo < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/root27/termongo/releases/download/v0.0.1/termongo_Darwin_x86_64.tar.gz"
      sha256 "1439fd46bbcfdaaad7bf31bf4e0640198d84d0f96770eb26530380a0cb590805"

      def install
        bin.install "termongo"
      end
    end
    on_arm do
      url "https://github.com/root27/termongo/releases/download/v0.0.1/termongo_Darwin_arm64.tar.gz"
      sha256 "6dec7c03b0548cc4f65b0dbd8569469480ca89bfa33c019bd01e2907e488fad3"

      def install
        bin.install "termongo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/termongo/releases/download/v0.0.1/termongo_Linux_x86_64.tar.gz"
        sha256 "bcca4450ec2b538e178f983709d350f81cebd57dadaaa8ec3e48638cbf71b56e"

        def install
          bin.install "termongo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/termongo/releases/download/v0.0.1/termongo_Linux_arm64.tar.gz"
        sha256 "b19bf9fddc9aafc6c0b4a3db225172c751a0125639729a1b88b36c0045136bbf"

        def install
          bin.install "termongo"
        end
      end
    end
  end
end
