# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termapi < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/root27/termapi/releases/download/v0.0.1/termapi_Darwin_x86_64.tar.gz"
      sha256 "cd70a57beb0661ea47499bfafc1bee11a3c55771fd1d285987947d97c7bfcecf"

      def install
        bin.install "termapi"
      end
    end
    on_arm do
      url "https://github.com/root27/termapi/releases/download/v0.0.1/termapi_Darwin_arm64.tar.gz"
      sha256 "fb9b1e2b238c3a6cc5e498c3a8cbf9ec5de78a6dbd9f76354ad8f0da587fc647"

      def install
        bin.install "termapi"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/termapi/releases/download/v0.0.1/termapi_Linux_x86_64.tar.gz"
        sha256 "491da7866a632dd642de7d1f3dc3277052acda338deab38627542128cebaac18"

        def install
          bin.install "termapi"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/root27/termapi/releases/download/v0.0.1/termapi_Linux_arm64.tar.gz"
        sha256 "59b91149e387e0ac87da73e6f96ece69b15a95f89f78a5accb16cc4e6c1730a5"

        def install
          bin.install "termapi"
        end
      end
    end
  end
end
