# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ymlgen < Formula
  desc ""
  homepage "https://github.com/root27/ymlgen"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/root27/ymlgen/releases/download/v1.0.0/ymlgen_1.0.0_darwin_amd64.tar.gz"
      sha256 "d62e980bac5b6b8d35b617077e65793c4fc2296e9824d632d16c3bdbc7ec4348"

      def install
        bin.install "ymlgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/root27/ymlgen/releases/download/v1.0.0/ymlgen_1.0.0_darwin_arm64.tar.gz"
      sha256 "77c17d6bfe92cd72dbba9bd82e8345b21f0ab50add5663b4fe2f60c1a04c0582"

      def install
        bin.install "ymlgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/root27/ymlgen/releases/download/v1.0.0/ymlgen_1.0.0_linux_amd64.tar.gz"
      sha256 "b114a4ef8020ff4545c5ed77811132c49b285611337f3db69129fc37e50a9dc1"

      def install
        bin.install "ymlgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/root27/ymlgen/releases/download/v1.0.0/ymlgen_1.0.0_linux_arm64.tar.gz"
      sha256 "9c34c722354076140f9388ad3ad77b09b1371abadc2cdad7de5d07c1d1d358ba"

      def install
        bin.install "ymlgen"
      end
    end
  end
end
